# Generated by Django 3.1.7 on 2022-06-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220605_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tipo',
            field=models.IntegerField(choices=[[0, 'consulta'], [1, 'reclamo'], [2, 'sugerencia'], [3, 'felicitaciones']]),
        ),
    ]
